### ISSUE TITLE
QTL for mysql

### ISSUE THREAD

**Issue by liufeijin** [znone/qtl#1]
I have include qtl_mysql.hpp
and some code as below 

#include "qtl_mysql.hpp"

MainWindow::MainWindow(QWidget *parent) :
    QMainWindow(parent),
    ui(new Ui::MainWindow)
{
    ui->setupUi(this);

    qtl::mysql::database db;
    db.open("localhost", "root", "", "test");
but build it and got errors as below

C:\Users\jeff\Documents\untitled5\qtl_mysql.hpp:4: error: 'mysql.h' file not found
C:\Users\jeff\Documents\untitled5\qtl_mysql.hpp:5: error: 'errmsg.h' file not found
Do i need more files for qt5.12 with qtl?
best regards,
jeff

**Comment by liufeijin** [comment]
你好：
我添加了mysql connector的包含文件后编译 有一个地方出现错位，能帮忙看看是什么问题吗
WINDOWS10 QT5.12环境
![1](https://user-images.githubusercontent.com/19425403/52625201-6cdb1480-2eeb-11e9-9818-bfbf3f1a24c1.png)

**Comment by znone** [comment]
在Windows下需要定义NOMINMAX，以关闭Windows的宏min和max。请参考test目录下的测试用例。

**Comment by liufeijin** [comment]
你好，我看了一下test得例子，你应该是利用stdafx.h 文件来定义NOMINMAX的吧，我在QT5里面把那行语句拷贝到我的头文件，发现不行。
QT里面怎么弄，我还不会。

**Comment by znone** [comment]
这个宏定义要在包含<windows.h>之前。你用QT 的话，就要放在QT的头文件之前。

**Comment by liufeijin** [comment]
你好，谢谢你的指点 ， 修改了宏定义的位置后那个问题消失了， 但是出现下面的错误
![TIM截图20190323203854](https://user-images.githubusercontent.com/19425403/54866196-f663e900-4dab-11e9-8db5-839dc0561281.png)
qing请帮忙看看什么问题

**Comment by znone** [comment]
你需要链接到MySQL C Connector（libmysql.lib）呀。

**Comment by liufeijin** [comment]
还需要libmsql.lib啊。 我以为不要的。
我在找一个不需要libmysql.lib的完全脱离该库的源代码驱动方式。
