### ISSUE TITLE
存储过程的执行方式

### ISSUE THREAD

**Issue by fmdsm** [znone/qtl#2]
1.使用query_multi执行存储过程，正常；
2.调用is_alive()，返回值为1，出错信息：Commands out of sync; you can't run this command now

**Comment by liufeijin** [comment]
可惜了。 这么好的头文件库，开发人员好久都没有更新了。

**Comment by znone** [comment]
> 1.使用query_multi执行存储过程，正常；
> 2.调用is_alive()，返回值为1，出错信息：Commands out of sync; you can't run this command now

能给出你的相关代码看看吗？

**Comment by znone** [comment]
> 可惜了。 这么好的头文件库，开发人员好久都没有更新了。

你有什么需求可以提出来。

**Comment by gxw8202** [comment]
template<typename Type, typename Ret, typename... Args>
inline auto make_values(Ret (Type::*)(Args...)) -> QTL_ARGS_TUPLE(Type, Args...)
{
	return QTL_ARGS_TUPLE(Type, Args...)();
};
VS2017下编译失败：参数包"Args"已引用，但未扩展
这个是什么原因啊

**Comment by znone** [comment]
能给出你的代码吗。仅从你贴的QTL代码，看不出问题出在哪里。
