### ISSUE TITLE
看起来很好，请问是线程安全的吗？

### ISSUE THREAD

**Issue by X-Crack** [znone/qtl#3]
之前一直使用POCO的sql中间件了，但是poco太庞大，随后就找到了这款中间件，如题不知道是否为线程安全。

**Comment by znone** [comment]
本库没有非常量的全局变量和非常量的静态成员变量，因此底层数据库客户端决定如何在多线程使用库。通常，不同的数据库连接是可以在多个线程中同时使用的，但是同一个连接只能同时被一个线程使用。

**Comment by X-Crack** [comment]
明白了，主要还是看worker是如何设计的吧。

**Comment by X-Crack** [comment]
query 方法能否更新一下，无论条件如何，只要查询到结果，就返回tue 没有查询到结果就返回false

然后在添加一个 std::forward_as_tuple 方法，

query("select uid from common_member where username = ?", std::forward_as_tuple(username))

感谢作者。

**Comment by znone** [comment]
你可能用错了。
query方法需要一个回调去去处理查询结果，所以并不需要通过返回值来报告是否查询到结果。
如果你不喜欢回调函数的方式，可以用result方法，它通过迭代的方式处理查询结果。

你可以使用forward_as_tuple来传递查询参数，这是没有问题的。在你的例子里，只有一个参数，可以不使用tuple。

**Comment by X-Crack** [comment]
嗯是的，result 方法 还要基于一个for，我在 query 下方自己又增加了一些方法。 感谢您的回答。

T* pThis = static_cast<T*>(this);
Command command = pThis->open_command(query_text, text_length);

这段代码 执行了2次拆构函数。。 建议修改为 std::unique_ptr 避免性能上的损失。

**Comment by znone** [comment]
你说的是result方法实现里面吗？那里用了移动函数去传递Command对象，不担心析构的代价。另外Command都是不可以复制的。使用指针需要在堆上创建对象，分配内存的代价比创建一个对象的代价更高些。

**Comment by X-Crack** [comment]
是的，确如您说的那样。query 的 callback 太爽了。希望作者多多维护此项目，好用的数据库中间件屈指可数。

**Comment by znone** [comment]
用这个库操作数据库，代码量是很少的。

**Comment by X-Crack** [comment]
32线程服务端负载均衡全线程占满 1000并发客户端 插入1000万数据花费1分10多秒。
比poco的执行效率高太多了。
